[build]
command = ""
publish = "."

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "."
entry-point = "."

[env.production]
name = "llmseoguide.com"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

[env.preview]
name = "preview.llmseoguide.com"
workers_dev = true

[env.preview.vars]
ENVIRONMENT = "preview" 