name = "ai-seo-analyzer"
main = "worker.js"
compatibility_date = "2023-01-01"

[vars]
ALLOWED_ORIGINS = ["http://localhost:3000", "https://llmlogs.com"]

# Add your OpenAI API key in the Cloudflare dashboard or using wrangler
# wrangler secret put OPENAI_API_KEY 