name = "bot-crawl-tracker"
main = "botcrawl.js"
compatibility_date = "2024-06-01"

[[kv_namespaces]]
binding = "BOT_CRAWLS"
id = "780850af34564d909d25164cef64fa67" # Replace this after you create the KV
